language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 7
    - 7.1

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer install --dev --prefer-source

script:
  - phpenv config-rm xdebug.ini
  - composer run phpcs
  - composer run phpstan
  - phpenv config-add xdebug.ini
  - composer run phpunit
